name = "ai-memo-app"
compatibility_date = "2024-07-15"
pages_build_output_dir = "dist"

# Local development configuration
[[d1_databases]]
binding = "DB"
database_name = "ai-memo-db"
database_id = "9ac44091-f0a9-4a38-b0ec-7ef3c313bb30"

[ai]
binding = "AI"

# Production environment for Cloudflare Pages
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "ai-memo-db"
database_id = "9ac44091-f0a9-4a38-b0ec-7ef3c313bb30"

[env.production.ai]
binding = "AI"

# Preview environment for Cloudflare Pages
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "ai-memo-db"
database_id = "9ac44091-f0a9-4a38-b0ec-7ef3c313bb30"

[env.preview.ai]
binding = "AI"

# JWT_SECRET moved to environment variables for security
# Development: Use .dev.vars file  
# Production: Set via Cloudflare Pages environment variables