name = "ai-memo-app"
compatibility_date = "2024-07-15"
pages_build_output_dir = "dist"

[env.production]
name = "ai-memo-app"
compatibility_date = "2024-07-15"

[env.development]
name = "ai-memo-app-dev"
compatibility_date = "2024-07-15"

[[d1_databases]]
binding = "DB"
database_name = "ai-memo-db"
database_id = "9ac44091-f0a9-4a38-b0ec-7ef3c313bb30"

[ai]
binding = "AI"

# JWT_SECRET moved to environment variables for security
# Development: Use .dev.vars file
# Production: Set via Cloudflare Workers environment variables